/* 
**  mod_kms_env.c -- Apache sample kms_env module
**  [Autogenerated via ``apxs -n kms_env -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory 
**  by running:
**
**    $ apxs -c -i mod_kms_env.c
**
**  Then activate it in Apache's httpd.conf file for instance
**  for the URL /kms_env in as follows:
**
**    #   httpd.conf
**    LoadModule kms_env_module modules/mod_kms_env.so
**    <Location /kms_env>
**    SetHandler kms_env
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /kms_env and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/kms_env 
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**  
**    The sample page from mod_kms_env.c
*/ 

#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "ap_config.h"

module AP_MODULE_DECLARE_DATA kms_env_module;

static void kms_env_register_hooks(apr_pool_t *p)
{
    //ap_hook_handler(kms_env_handler, NULL, NULL, APR_HOOK_MIDDLE);
}

/* Dispatch list for API hooks */
AP_DECLARE_MODULE(kms_env) = {
    STANDARD20_MODULE_STUFF, 
    NULL,                  /* create per-dir    config structures */
    NULL,                  /* merge  per-dir    config structures */
    NULL,                  /* create per-server config structures */
    NULL,                  /* merge  per-server config structures */
    NULL,                  /* table of config file commands       */
    kms_env_register_hooks  /* register hooks                      */
};

